# Config file for automatic testing at travis-ci.org

sudo: false

language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

cache:
  directories:
    - $HOME/thrift
    - $HOME/nanomsg

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install tox

# command to run tests
script:
  - tox -e $TOX_ENV

after_success:
  # Report coverage results to codecov.io
  - pip install codecov
  - codecov
